version: '3.3'
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php73
    volumes:
      - ./:/var/www/html/
    ports:
      - 8080:80
    links:
      - mysql
  mysql:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1'
    ports:
      - 6033:3306